//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrderType } from './OrderType';

export class CreateOrderModel
{
    public orderType: OrderType;
    public productTypeId: number;
    public price: number;
    public purchaserPhoneNumber: string;
    public purchaserEmail: string;
}
